<?php
/**
 * Created by PhpStorm.
 * User: fcoco
 * Date: 28/05/2018
 * Time: 11:34
 */

namespace App\Entity;

use App\Entity\TipoDeAto;
use App\Entity\TipoDeProcesso;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class LotacaoFormType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('descricao', TextType::class)
            ->add('tiposdeato', EntityType::class, array(
                    'placeholder' => 'Selecione...',
                    'class' => TipoDeAto::class,
                    'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('u')
                            ->orderBy('u.descricao', 'ASC');
                    },
                    'choice_label' => 'descricao',
                    'required' => false,
                    'expanded' => true,
                    'multiple' => true,
                    'empty_data' => null
                )
            )
            ->add('tiposdeprocesso', EntityType::class, array(
                    'placeholder' => 'Selecione...',
                    'class' => TipoDeProcesso::class,
                    'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('u')
                            ->orderBy('u.descricao', 'ASC');
                    },
                    'choice_label' => 'descricao',
                    'required' => false,
                    'expanded' => true,
                    'multiple' => true,
                    'empty_data' => null
                )
            );

    }

    public function configureOptions(OptionsResolver $resolver){
        $resolver->setDefaults(array(
            'data_class' => Lotacao::class
        ));
    }

}