# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'pt_BR'
    documents_directory: '%kernel.project_dir%/public/uploads/documents/'
    images_directory: '%kernel.project_dir%/public/uploads/images/'
    mailer_user: 'procuradoriageralmunicipio@gmail.com'
    mailer_sender: 'Procuradoria Geral do Municipio de Teresina'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    notifyCommand.service:
        public: true
        class: App\Services\NotifyCommand

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    employeeformtype_entitymanager.service:
        class: App\Entity\dai\rh\EmployeeFormType
        arguments:
        entityManager: "@doctrine.orm.entity_manager"

    estado_entitymanager.service:
        class: App\Entity\dai\rh\Estado
        arguments:
        em: "@doctrine.orm.entity_manager"

    lotacaoformtype_entitymanager.service:
        class: App\Entity\Lotacao
        arguments:
        em: "@doctrine.orm.entity_manager"

    redirect.after.login:
        class: App\Redirection\AfterLoginRedirection
        arguments: ['@router']

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:                               # this lines
        mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_sender%"
    registration:
        form:
            type: App\Entity\UserFormType
    resetting:
        email:
            from_email:
                address:        "%mailer_user%"
                sender_name:    "%mailer_sender%"
    profile:
        form:
            type: App\Entity\ProfileFormType

framework:
    default_locale: 'pt_BR'
    translator:
        fallbacks: ['%locale%']

cmen_google_charts:
    version: "current"
    language: "pt"

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'

knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20 # In seconds